services:
  db: 
    image: postgres:16.0
    environment:
      POSTGRES_USERNAME: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - 5432:${PG_PORT}

  app:
    build:
      dockerfile: Dockerfile
    depends_on:
      - migrations
    ports:
      - 127.0.0.1:3000:3000
    environment:
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      PG_USERNAME: ${PG_USERNAME}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DATABASE: ${PG_DATABASE}
  
  migrations:
    build:
      context: .
    links:
      - 'db'
    depends_on:
      - 'db'
    command: ['npm', 'run', 'setup']
    environment:
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      PG_USERNAME: ${PG_USERNAME}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DATABASE: ${PG_DATABASE}
